# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Engenieer/Documents/LCSEL_git/LCSEL/CLK_FIFO/CLK_FIFO.srcs/sources_1/ip/fifo/fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo || ORIG_REF_NAME==fifo} -quiet] -quiet
