# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/Clk_PIC_TOP/Clk_PIC_TOP.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Clk_PIC_TOP || ORIG_REF_NAME==Clk_PIC_TOP} -quiet] -quiet
