@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Tue Dec 31 02:02:58 +0100 2019
REM SW Build 2700185 on Thu Oct 24 18:46:05 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto dcfdd1d53d484be69a4dd16fdff1e5ec --incr --debug typical --relax --mt 2 -L xil_defaultlib -L fifo_generator_v13_2_5 -L work -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot PICtop_tb_behav xil_defaultlib.PICtop_tb xil_defaultlib.glbl -log elaborate.log"
call xelab  -wto dcfdd1d53d484be69a4dd16fdff1e5ec --incr --debug typical --relax --mt 2 -L xil_defaultlib -L fifo_generator_v13_2_5 -L work -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot PICtop_tb_behav xil_defaultlib.PICtop_tb xil_defaultlib.glbl -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
