@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun Nov 17 19:06:05 +0100 2019
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim RS232top_TB_behav -key {Behavioral:sim_1:Functional:RS232top_TB} -tclbatch RS232top_TB.tcl -view C:/Users/Engenieer/Documents/LCSEL_git/LCSEL/RS232_COMPLETE/RS232top_TB_behav.wcfg -log simulate.log"
call xsim  RS232top_TB_behav -key {Behavioral:sim_1:Functional:RS232top_TB} -tclbatch RS232top_TB.tcl -view C:/Users/Engenieer/Documents/LCSEL_git/LCSEL/RS232_COMPLETE/RS232top_TB_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
